In [1]:
import cx_Oracle
import pandas as pd
connection = cx_Oracle.connect(user='scott', password='tiger', dsn='192.168.119.119:1521/dink11.dbsvr')

In [15]:
cursor = connection.cursor()
sql="select * from card_history where card_his_date between to_char('23/03/01') and to_char('23/06/01')"
cursor.execute(sql)

rows = cursor.fetchall()
cursor.close()
columns = ['Card His ID', '카드번호', 'category_id', '거래지역', '상점명', '거래날짜', '거래시간', '거래금액']
data = pd.DataFrame(rows, columns=columns)
data

,Card His ID,카드번호,category_id,거래지역,상점명,거래날짜,거래시간,거래금액
0,269,2568-9238-5337-7494,hb053,충청북도,남김권,2023-04-22,19:02:00,98000
1,271,2568-9238-5337-7494,hb073,충청북도,(유) 최,2023-03-19,19:04:00,57000
2,273,2568-9238-5337-7494,hb022,충청북도,류이,2023-05-04,19:28:00,6500
3,275,2568-9238-5337-7494,hb016,충청북도,김이,2023-04-20,20:47:00,10000
4,277,2568-9238-5337-7494,hb071,충청북도,(유) 이,2023-05-31,17:06:00,25000
...,...,...,...,...,...,...,...,...
600295,1142267,8400-4787-7962-6317,hb041,충청남도,주식회사 김류김,2023-05-30,14:27:00,66000
600296,1142269,8400-4787-7962-6317,hb024,충청남도,김강박,2023-04-21,10:21:00,57000
600297,1142271,8400-4787-7962-6317,hb023,충청남도,남김,2023-03-26,20:17:00,21000
600298,1142273,8400-4787-7962-6317,hb011,충청남도,강박류,2023-03-19,16:36:00,46000
600299,1142275,8400-4787-7962-6317,hb021,충청남도,(유) 김,2023-03-05,17:47:00,32000

In [16]:
cursor = connection.cursor()
sql="select * from category"
cursor.execute(sql)

rows = cursor.fetchall()
cursor.close()
columns = ['category_id','대분류','중분류','소분류']
category = pd.DataFrame(rows, columns=columns)
category

   category_id        대분류        중분류         소분류
0        hb011      요식/유흥         요식          한식
1        hb012      요식/유흥         요식    일식/중식/양식
2        hb013      요식/유흥         요식         제과점
3        hb014      요식/유흥         요식       커피전문점
4        hb015      요식/유흥         요식       패스트푸드
5        hb016      요식/유흥         유흥         노래방
6        hb017      요식/유흥         유흥      기타유흥업소
7        hb018      요식/유흥         유흥        유흥주점
8        hb021         유통         유통         백화점
9        hb022         유통         유통         할인점
10       hb023         유통         유통        슈퍼마켓
11       hb024         유통         유통        생활잡화
12       hb025         유통         유통         편의점
13       hb031      음/식료품      음/식료품         정육점
14       hb032      음/식료품      음/식료품        농수산물
15       hb033      음/식료품      음/식료품     기타음/식료품
16       hb041      의류/잡화      의복/의류       의복/의류
17       hb042      의류/잡화      패션/잡화       패션/잡화
18       hb043      의류/잡화      패션/잡화          안경
19       hb044      의류/잡화      패션/잡화         귀금속
20       hb051  스포츠/문화/레저        스포츠     실내골프/헬스
21       hb052  스포츠/문화/레저        스포츠     실외골프/스키
22       hb053  스포츠/문화/레저        스포츠       스포츠시설
23       hb054  스포츠/문화/레저         레저      종합레저시설
24       hb055  스포츠/문화/레저         문화       영화/공연
25       hb056  스포츠/문화/레저         문화       취미/오락
26       hb057  스포츠/문화/레저         문화          서점
27       hb061      여행/교통         숙박       호텔/콘도
28       hb062      여행/교통         숙박  모텔/여관/기타숙박
29       hb063      여행/교통         여행         여행사
30       hb064      여행/교통         여행         면세점
31       hb071         미용         미용       미용서비스
32       hb072         미용         미용         미용실
33       hb073         미용        화장품         화장품
34       hb081   가정생활/서비스        서비스       생활서비스
35       hb082   가정생활/서비스        서비스         세탁소
36       hb083   가정생활/서비스        서비스       업무서비스
37       hb091      교육/학원         학원          학원
38       hb092      교육/학원       유아교육        유아교육
39       hb093      교육/학원       교육용품        교육용품
40       hb101         의료         병원        종합병원
41       hb102         의료         병원        일반병원
42       hb103         의료         병원        치과병원
43       hb104         의료         병원         한의원
44       hb105         의료         약국          약국
45       hb111      가전/가구      가전/가구          가전
46       hb112      가전/가구      가전/가구          가구
47       hb113      가전/가구      가전/가구     기타가전/가구
48       hb121        자동차  자동차서비스/용품      자동차서비스
49       hb122        자동차  자동차서비스/용품       자동차용품
50       hb131         주유         주유         주유소
51       hb132         주유         주유         LPG

In [17]:

data_with_subcategory = data.merge(category, on='category_id', how='left')
data_with_subcategory

,Card His ID,카드번호,category_id,거래지역,상점명,거래날짜,거래시간,거래금액,대분류,중분류,소분류
0,269,2568-9238-5337-7494,hb053,충청북도,남김권,2023-04-22,19:02:00,98000,스포츠/문화/레저,스포츠,스포츠시설
1,271,2568-9238-5337-7494,hb073,충청북도,(유) 최,2023-03-19,19:04:00,57000,미용,화장품,화장품
2,273,2568-9238-5337-7494,hb022,충청북도,류이,2023-05-04,19:28:00,6500,유통,유통,할인점
3,275,2568-9238-5337-7494,hb016,충청북도,김이,2023-04-20,20:47:00,10000,요식/유흥,유흥,노래방
4,277,2568-9238-5337-7494,hb071,충청북도,(유) 이,2023-05-31,17:06:00,25000,미용,미용,미용서비스
...,...,...,...,...,...,...,...,...,...,...,...
600295,1142267,8400-4787-7962-6317,hb041,충청남도,주식회사 김류김,2023-05-30,14:27:00,66000,의류/잡화,의복/의류,의복/의류
600296,1142269,8400-4787-7962-6317,hb024,충청남도,김강박,2023-04-21,10:21:00,57000,유통,유통,생활잡화
600297,1142271,8400-4787-7962-6317,hb023,충청남도,남김,2023-03-26,20:17:00,21000,유통,유통,슈퍼마켓
600298,1142273,8400-4787-7962-6317,hb011,충청남도,강박류,2023-03-19,16:36:00,46000,요식/유흥,요식,한식
600299,1142275,8400-4787-7962-6317,hb021,충청남도,(유) 김,2023-03-05,17:47:00,32000,유통,유통,백화점

In [18]:
data_with_subcategory.groupby('대분류')['거래금액'].mean().sort_values(ascending=False)

대분류
가전/가구        829657.256067
교육/학원        367791.126816
여행/교통        319465.637450
주유           168086.154747
미용           166854.503464
의류/잡화        148772.629194
자동차           84525.077706
가정생활/서비스      60130.231555
스포츠/문화/레저     51121.518317
음/식료품         37472.704824
유통            33965.133469
요식/유흥         21768.214826
의료            16996.457442
Name: 거래금액, dtype: float64

In [19]:
data_with_subcategory.groupby('대분류')['거래금액'].count().sort_values(ascending=False)

대분류
요식/유흥        161805
스포츠/문화/레저     98135
유통            74137
의료            40451
의류/잡화         37076
음/식료품         34017
미용            31176
여행/교통         28112
가정생활/서비스      27812
주유            20498
가전/가구         20190
자동차           14156
교육/학원         12735
Name: 거래금액, dtype: int64