In [67]:
import cx_Oracle
import pandas as pd
connection = cx_Oracle.connect(user='scott', password='tiger', dsn='192.168.119.119:1521/dink11.dbsvr')
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import tqdm

In [68]:
cursor = connection.cursor()
sql="select * from cardhistory where cardId='9440-9469-2724-7629'"
cursor.execute(sql)

rows = cursor.fetchall()
cursor.close()
columns = ['cardHisId','cardId', 'categoryBig', 'categorySmall','regionName', 'store', 'cardHisDate', 'cardHisTime', 'amount']
data = pd.DataFrame(rows, columns=columns)

In [69]:
# 인코딩한 값 가져오기
cursor = connection.cursor()
sql="select regionName, SEOULTTOREGIONDISTANCE from region"
cursor.execute(sql)

rows = cursor.fetchall()
columns = ['regionName','seoulTorReionDistance']
region = pd.DataFrame(rows, columns=columns)

cursor = connection.cursor()
sql="select categorySmall, barToEmbedding from category"
cursor.execute(sql)

rows = cursor.fetchall()
columns = ['categorySmall','barToEmbedding']
category = pd.DataFrame(rows, columns=columns)

In [70]:
data['categorySmall'] = data['categorySmall'].replace(category.set_index('categorySmall')['barToEmbedding'])
data['regionName'] = data['regionName'].replace(region.set_index('regionName')['seoulTorReionDistance'])
data['cardHisTime'] = data['cardHisTime'].str.split(':').str[0].astype(int)
data
# data = data.drop('categoryBig', axis=1)

,cardHisId,cardId,categoryBig,categorySmall,regionName,store,cardHisDate,cardHisTime,amount
0,2508200,9440-9469-2724-7629,요식/유흥,0.247283,40,양김남,2023-03-23,18,1800
1,2508201,9440-9469-2724-7629,미용,0.238686,1,박박김,2023-08-06,12,74000
2,2508202,9440-9469-2724-7629,음/식료품,0.230959,1,(주) 윤,2023-05-25,12,44000
3,2508203,9440-9469-2724-7629,스포츠/문화/레저,0.162976,1,(유) 이김김,2023-06-19,13,30800
4,2508204,9440-9469-2724-7629,의류/잡화,0.140980,1,김전,2023-05-08,14,98000
...,...,...,...,...,...,...,...,...,...
495,2508695,9440-9469-2724-7629,스포츠/문화/레저,0.066467,132,(유) 이김황,2023-07-26,20,20000
496,2508696,9440-9469-2724-7629,요식/유흥,0.099979,1,박김최,2023-03-04,17,25000
497,2508697,9440-9469-2724-7629,음/식료품,0.282791,1,(주) 황안최,2023-09-01,18,27000
498,2508698,9440-9469-2724-7629,유통,0.211717,40,유한회사 손,2023-07-14,14,45000
499,2508699,9440-9469-2724-7629,요식/유흥,0.284030,1,김양,2023-04-06,21,9200

In [72]:
data.to_csv("encodingData_7629.csv",encoding='utf-8')

In [73]:
data=pd.read_csv("encodingData_7629.csv")
print(data['regionName'].to_list())

[40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 40, 40, 1, 1, 1, 1, 1, 40, 1, 40, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 1, 1, 1, 1, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 1, 1, 1, 1, 1, 1, 40, 1, 1, 1, 1, 1, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 1, 1, 1, 1, 1, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 132, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 1, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 132, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 132, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 1, 1, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 1, 1, 1, 1, 1, 132, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 132, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 1, 1, 1, 1, 1, 1, 40, 40, 1, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 1, 1, 1, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 40, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 40, 1, 1, 132, 1, 132, 132, 1, 1, 40, 1]

In [50]:
practice_data=data[['categorySmall','regionName','cardHisTime','amount']].values
practice_data

array([[2.47283027e-01, 1.00000000e+00, 1.80000000e+01, 1.80000000e+03],
       [2.38685727e-01, 1.00000000e+00, 1.20000000e+01, 7.40000000e+04],
       [2.30958968e-01, 1.00000000e+00, 1.20000000e+01, 4.40000000e+04],
       ...,
       [2.82790810e-01, 1.00000000e+00, 1.80000000e+01, 2.70000000e+04],
       [2.11716667e-01, 1.00000000e+00, 1.40000000e+01, 4.50000000e+04],
       [2.84029752e-01, 1.00000000e+00, 2.10000000e+01, 9.20000000e+03]])

In [53]:
from sklearn.mixture import GaussianMixture

n_components = 5
GMM_columns = ['categorySmall','regionName','cardHisTime','amount']
# GMM_columns = ['embedding', '거래지역', '거래시간', '거래금액']

gmm = GaussianMixture(n_components=n_components)


gmm.fit(practice_data)
likelihoods = gmm.score_samples(practice_data)
likelihoods

array([ -6.11009147,  -7.98512127,  -7.1102153 ,  -6.01606074,
        -7.7199492 ,  -7.47014045,  -7.62680721,  -6.38057333,
        -5.53231967,  -7.50021054,  -7.49267131,  -6.3369938 ,
        -7.45656734,  -5.6264358 ,  -6.26130248,  -7.59665872,
        -7.99851069,  -5.75294438,  -4.94120666,  -4.97581752,
        -7.62847493,  -4.91694009,  -5.22819947,  -9.0277409 ,
        -8.48492474,  -7.35690021,  -6.20575092, -10.83741977,
        -7.23357283,  -6.06343934,  -7.99003913, -10.91960122,
        -9.9055683 ,  -6.06313795, -13.20773861,  -4.74806345,
        -6.22406551,  -4.42128893,  -5.22400957,  -7.47867062,
        -5.60627275,  -8.58480066,  -7.63030621,  -6.97992648,
        -5.16380754,  -6.82801019,  -6.28857038,  -5.37954856,
        -7.95577168,  -6.24128465, -11.21885431,  -9.61621026,
        -5.12577588,  -6.02565164,  -9.58711404,  -6.44226195,
        -6.92006975,  -7.03981807,  -7.67882769,  -5.84525978,
        -5.60302448,  -7.72242032,  -6.62929874, -10.83166902,
        -7.30477984,  -6.53975354,  -6.15304708,  -6.28857038,
        -7.05855055,  -4.59599907, -11.80680469,  -7.55866644,
        -8.30020922,  -6.86337888,  -6.41492892,  -5.47982893,
        -5.35006762, -10.38059451,  -5.16109729,  -5.89306366,
        -6.07542768,  -7.31321006,  -6.40535064,  -9.03685615,
        -7.59665872,  -5.05365091,  -9.23197134,  -7.87450555,
        -4.31887792,  -5.50820511,  -7.41284729,  -8.08797388,
        -7.42969623,  -5.05569374,  -7.52305891,  -8.97299522,
        -6.04893376,  -7.07569166,  -8.0133854 ,  -7.02695385,
        -5.80358988,  -7.71193404,  -7.35590677,  -5.19016731,
        -4.89888697,  -7.46306654,  -6.26130248,  -7.25373662,
        -7.12252208,  -6.9020531 ,  -6.66769397,  -7.29887176,
        -5.60783132,  -9.29377914,  -5.06138682,  -5.8783375 ,
        -6.36100648,  -7.03374368,  -7.57584499,  -7.12252208,
        -6.07525047,  -7.5567371 ,  -4.64368313,  -6.49623204,
        -5.00857122,  -5.90162986,  -4.87410758,  -6.9020531 ,
        -7.31968669,  -9.84191144,  -7.29268697,  -8.42340955,
        -7.16292532,  -4.47125625,  -6.88622527,  -9.36915999,
        -6.403487  ,  -7.69944909,  -7.58024462,  -4.42128893,
        -9.65620752,  -8.08010436,  -5.20754918, -10.33119796,
        -5.60161412,  -8.50302735,  -4.97527851,  -7.38833536,
        -5.54235866,  -6.60123018,  -7.5567371 ,  -4.91711103,
        -8.63396494,  -5.16014373,  -8.18901132,  -4.94120666,
        -8.38373587,  -6.82291589,  -7.34268923,  -6.40619808,
        -7.61400446,  -5.33625102,  -6.19046601,  -6.0509466 ,
        -6.42878256,  -7.15881077,  -7.44693275,  -7.71835781,
        -6.3043264 ,  -6.72893423,  -5.8388837 ,  -6.86317294,
        -8.2821229 ,  -8.09318025,  -5.82024198,  -6.99734337,
        -6.46360327,  -7.23700002,  -9.88909725,  -5.85706874,
        -7.21535356,  -7.77720103,  -8.15760393,  -6.12246691,
        -8.42498185,  -5.86027276,  -8.77129125, -10.44536824,
        -4.93209558,  -7.40114413,  -5.36930063,  -6.02209044,
        -6.7274821 ,  -6.39276678,  -6.72255252,  -6.58006446,
        -5.13905   ,  -7.82986071,  -6.72003551,  -6.0555184 ,
        -7.79469326,  -6.25308654,  -9.53040482,  -7.37864039,
        -6.25308654,  -5.0888096 ,  -9.00234884,  -5.65244684,
        -6.28067515,  -7.86208515,  -5.15544736,  -7.23595201,
        -9.06676548,  -6.69016647,  -5.34403935,  -5.49223598,
        -7.05855055,  -7.11341175,  -4.93639948,  -6.42160951,
        -6.72003551,  -7.25041989,  -9.95811755,  -5.73153226,
        -9.52391747,  -7.84015133,  -8.06562558,  -7.66275921,
        -5.00857122,  -7.38990521,  -8.04859292,  -6.20575092,
        -7.21393509,  -8.64554082,  -6.71137833,  -9.00749703,
        -6.62287901,  -9.18693483,  -9.13334556,  -8.74780047,
        -9.21626384,  -9.04851821,  -9.96797066,  -5.89187365,
        -7.47954457, -10.53900425,  -6.54439277,  -7.62147843,
        -5.92838719,  -6.25530093,  -8.12853608,  -7.55476529,
        -5.75294438,  -7.33424917,  -5.77781282,  -7.07115492,
        -8.20237204,  -5.79064102,  -9.0293689 ,  -7.37495255,
        -9.04728981,  -7.66336892,  -8.18664625,  -6.08285256,
        -5.15544736,  -6.09764534,  -9.37737558,  -7.8936988 ,
        -8.67292027,  -7.48944419,  -6.28393963,  -6.96977743,
        -7.20211408,  -7.00453309,  -6.78987235,  -5.89526285,
        -7.29092845,  -4.39186652,  -5.43658975,  -5.76253563,
        -6.50230253,  -9.41686294,  -6.46164517,  -5.58326596,
        -8.2909277 ,  -4.74806345,  -6.84617296,  -5.96317718,
        -4.97581752,  -6.28857038,  -9.7211663 ,  -6.89601989,
        -7.44765325,  -8.21596096,  -5.18034736,  -5.22740091,
        -7.88711931,  -5.22740091,  -5.4338508 ,  -5.16380754,
        -7.68688093, -10.52654482,  -5.93370695,  -5.92409649,
        -4.94332537,  -8.22144756,  -4.92063342,  -5.91106649,
        -7.78532374,  -7.20211408,  -7.35057897,  -6.98185133,
        -6.09517192,  -6.56512862,  -6.72772608,  -6.27417348,
        -8.30237333,  -4.63003489,  -6.15473481,  -6.46164517,
        -7.75168436,  -4.96082366,  -6.29276357,  -6.6747875 ,
        -5.42342684,  -8.06036815,  -5.00139502,  -6.90495214,
        -4.91908269,  -6.74809315,  -4.75928379,  -6.403487  ,
        -6.58445845,  -5.79189706,  -7.08492473,  -7.57950193,
        -7.77416452,  -8.15622294,  -8.01804476,  -9.67761919,
        -5.34969669,  -5.4338508 ,  -7.41246552,  -8.07821712,
        -9.52707306,  -6.5947846 ,  -4.52383315,  -8.43467772,
        -7.05822953,  -9.92327739,  -6.29842829,  -6.57738693,
        -5.36191626, -10.69452081,  -5.96960537,  -4.94019861,
        -5.37652109,  -8.742271  ,  -5.86920473,  -6.17524472,
        -5.54732936,  -4.62947431, -10.30030624,  -5.82031469,
        -6.09457724,  -6.14463127,  -8.18464002,  -6.29635851,
        -9.11249387,  -8.92803342,  -6.3035376 ,  -6.36010042,
        -7.38183994,  -5.53394113,  -7.51282971,  -5.91542965,
        -7.38675303,  -7.94960487,  -6.43792841,  -4.9181404 ,
       -12.24943822,  -7.00592816,  -7.26141794,  -9.445452  ,
        -5.44882814,  -7.36309513,  -6.22530533,  -6.58231653,
        -5.96691474,  -5.54732936,  -6.84147841,  -5.83807434,
        -7.4873171 ,  -8.44629826,  -4.43400773,  -4.4492295 ,
        -4.85972548,  -7.43523626,  -5.12493773,  -5.47842847,
        -5.05569374,  -6.68298769,  -7.27097791,  -9.9657876 ,
        -7.67418016,  -7.00571551,  -6.39276678, -11.18264837,
        -4.79718626,  -6.0509466 ,  -9.43794355,  -4.98893367,
        -8.94461076,  -6.62587298,  -9.48741469,  -5.15544736,
        -8.1774406 , -10.53825703,  -9.21611224,  -6.95480505,
        -6.78987235,  -5.98928419,  -6.66727195,  -6.45883141,
       -11.28997583,  -7.58163714,  -6.41036405,  -4.81095374,
        -6.08775035,  -6.89601989,  -8.63396494,  -5.24421789,
        -6.45680168,  -6.66727195,  -7.02054387,  -4.9032199 ,
        -7.20211408,  -5.79202622,  -7.05855055,  -6.30252913,
        -5.99155139,  -8.13088358,  -6.69016647,  -7.26141794,
        -6.46116691,  -7.50810156,  -7.44920222,  -5.34128863,
        -6.71137833, -11.60475906,  -5.2141789 ,  -7.8176929 ,
        -4.26590621,  -6.01515493,  -7.26695672,  -4.85427801,
        -5.14139933,  -6.62287901,  -5.57081814,  -8.90571135,
        -7.23425009,  -6.46164517, -10.07848454,  -5.61520283,
       -10.22479953,  -8.31599515,  -9.50179505,  -7.62680721,
        -5.47529856,  -6.76239253,  -7.59541617,  -8.42640093,
        -6.45551398,  -5.22467886,  -7.41418955,  -5.74746   ,
        -6.26130248,  -8.92499746,  -4.81998478,  -7.61457067,
        -8.69634111,  -6.10631449,  -6.84184033,  -6.36646508,
        -8.43165067,  -6.53669517,  -8.77408197,  -8.60935789,
        -6.56872865,  -6.28723727, -10.27220466,  -4.69193995,
        -4.95978389,  -8.27901252,  -8.50466179,  -7.00767431,
        -5.89526285,  -7.87223541,  -6.48000402,  -5.56248748])

In [ ]:
for feature in GMM_columns:
        # Reshape the data to 2D array
        gmm = GaussianMixture(n_components=n_components)  # You can adjust the number of components as needed
        gmm.fit(data)
        predicted_labels = gmm.predict(data)
        # print(predicted_labels)
        print(data)
        print(len(np.unique(data)))
        print(len(data))
        print(data.min())
        print(data.max())

        # Create a range of values for plotting the PDFs
        x = np.linspace(data.min(), data.max(), 1000)

        # Compute the PDF (Probability Density Function) using the GMM
        pdf = np.exp(gmm.score_samples(x.reshape(-1, 1)))
        # Plot the data and the estimated GMM
        plt.figure()
        plt.hist(data, bins=100, density=True, alpha=0.5, color='blue', label='Data Histogram')
        plt.plot(x, pdf, '-r', label='GMM PDF')
        plt.title(f'GMM for {feature}')
        plt.xlabel(feature)
        plt.ylabel('Probability Density')
        plt.legend()
        plt.show()